### ISSUE TITLE
isoparse TypeError cuando no existe transaction_date

### ISSUE THREAD

**Issue by bimartinez** [fintoc-com/fintoc-python#1]
Hola!

Al momento de utilizar `account.update_movements`, si el argumento `transaction_date` que recibe un `Movement` al instanciarse es `None`, entonces `isoparse` levanta un `TypeError` al intentar parsear el `None` y por lo tanto los movimientos no logran cargarse.

**Comment by nebil** [comment]
Nice catch, @bimartinez! I tested only with movements that had a transaction date.

**PS.** By the way, glad to see you around. 😊
