### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by CAUN94** [fintoc-com/fintoc-python#3]
Hello, there is a form to see the comments of the movements?

**Comment by lezorich** [comment]
Hey! 

We have the movement's comment [in our API ](https://fintoc.com/docs#objeto-movement), but we haven't updated the client yet. 

I can update the client to the latest version of our API by the end of the day 😊

**Comment by CAUN94** [comment]
Perfect

**Comment by lezorich** [comment]
@CAUN94 we just released [version 0.2.0](https://pypi.org/project/fintoc/0.2.0/). You now can access the [movement's comment if available](https://fintoc.com/docs#movimientos).
